### PR TITLE
Added monaco as supported platform

### PR DESCRIPTION
**Pull request by wmanth**
As my DS216play is not supported currently, I added the STM Monaco ARM platform.

### CODE REVIEW

**Comment by wmanth** [comment]
I was expecting GitHub Actions to build and check the PR, but seems it doesn't. Anything done wrong?

**Comment by fthouraud** [comment]
I think there's another modification required in the `repo/index.js` too.

I'm eager to have this version too. @oznu would you have time to take a look at this one please?

**Comment by NorthernMan54** [comment]
For this pull request, is it good to go or does it need more work or testing?

**Comment by wmanth** [comment]
> For this pull request, is it good to go or does it need more work or testing?

I built a test package for the _Monaco_ platform in my [forked repo releases](https://github.com/wmanth/homebridge-syno-spk/releases) but the Homebridge server doesn't start up. Checking on command line I believe the reason is:

- The build script downloads the latest LTS node binary, which at the time of writing is v18.12.0 https://github.com/homebridge/homebridge-syno-spk/blob/e2d91d81e442f1d8ffdc271df920fe9dc397af94/.ci/build-package.sh#L13
- The v18.12.0 node binary expects a higher glibc library version then provided by the system, as in nvm-sh/nvm#2972

A workaround is using the Node.js v18 installation instead the node binary installed by this script.

**Pull request closed without merging**
